// src/lit/cypress-lit-component-helper.ts
/// <reference types="cypress" />
import { getContainerEl } from "@cypress/mount-utils";
import { html, LitElement, render, TemplateResult } from "lit";
/**
 * @class CypressLitComponentHelper was designed designed for mounting lit components
 * @classdes CypressLitComponentHelper exposes the following public properties:
 * @property when - enables mounting of a li component
 */
export class CypressLitComponentHelper {
  public given = {};
  public when = {
    /**
     * Mount a LitElement web component
     * @example
     * litComponentHelper.when.mount<SpinnerElement>(
        new SpinnerElement(),
        html`<edf-spinner size="${this.props.size}" type="${this.props.type}" label="${this.props.label}"></edf-spinner>`
      );
     * @template T - element type
     * @param element 
     * @param template 
     */
    mount: <T extends LitElement>(element: T, template: TemplateResult) => {
      const target = getContainerEl();

      render(template, target);

      return (
        cy
          .wait(0, { log: false })
          .then(() => {
            const mountMessage = `<${String(element.constructor.name)} ... />`;

            Cypress.log({
              name: "mount",
              message: [mountMessage]
            })
              .snapshot("mounted")
              .end();
          })
          .get("[data-cy-root]", { log: false })
          .children({ log: false })
          .first({ log: false })
          // @ts-ignore
          .shadow({ log: false })
      );
    },
    unmount: <T extends LitElement>(element: T) =>
      this.when.mount(element, html`<slot></slot>`)
  };
  public get = {};
}

// src/react/cypress-react-component-helper.ts
/// <reference types="cypress" />
import { mount } from "cypress/react18";
import type {
  Attributes,
  ComponentClass,
  FunctionComponent,
  ReactNode
} from "react";
import React from "react";

/**
 * @class CypressReactComponentHelper was designed designed for mounting react components
 * @classdes CypressReactComponentHelper exposes the following public properties:
 * @property when - enables mounting of a React component
 * @property get - enables getting the mounted component
 */
export class CypressReactComponentHelper {
  private component: React.ReactNode;

  public when = {
    /**
     * Mount a react component
     * @param type
     * @param props
     * @param children
     */
    mount: <
      P extends {},
      T extends
        | FunctionComponent<P>
        | ComponentClass<P>
        | ((props: P) => JSX.Element)
    >(
      type: T | string,
      props?: (Attributes & P) | null,
      ...children: ReactNode[]
    ) => {
      const mountResponse = mount(
        React.createElement(type, props, ...children)
      );
      mountResponse.its("component").then((component: React.ReactNode) => {
        this.component = component;
      });
    }
  };
  public get = {
    /**
     * Get mounted component
     * @returns {ReactNode}
     */
    component: () => this.component
  };
}
